import os

os.environ.setdefault("DIRECTOR_ENVIRONMENT", "test")
os.environ.setdefault("DIRECTOR_AUTH_REQUIRED", "false")
os.environ.setdefault("DIRECTOR_AUTH_SECRET", "test-auth-secret-change-me")
os.environ.setdefault("DIRECTOR_DATABASE_URL", "sqlite+pysqlite:///./test_director.db")
os.environ.setdefault("DIRECTOR_UPLOAD_DIR", "./.test-data/uploads")
os.environ.setdefault("DIRECTOR_OUTPUT_DIR", "./.test-data/outputs")
os.environ.setdefault("DIRECTOR_OBJECT_STORAGE_PROVIDER", "local")
os.environ.setdefault("DIRECTOR_OBJECT_STORAGE_LOCAL_DIR", "./.test-data/object-storage")
os.environ.setdefault("DIRECTOR_MULTIPART_PART_BYTES", "5242880")
os.environ.setdefault("DIRECTOR_MAX_UPLOAD_BYTES", "12582912")
os.environ.setdefault("DIRECTOR_RESUMABLE_REQUEST_BYTES", "65536")
os.environ.setdefault("DIRECTOR_EMAIL_PROVIDER", "database")
os.environ.setdefault("DIRECTOR_STARTER_CREDITS", "100")
os.environ.setdefault("DIRECTOR_BILLING_ENABLED", "true")
os.environ.setdefault("DIRECTOR_AUTO_CREATE_SCHEMA", "true")
